
-- =========================
-- 0) DROPS
-- =========================
DROP TABLE CONFERENCIA_SALA CASCADE CONSTRAINTS;
DROP TABLE SALA CASCADE CONSTRAINTS;
DROP TABLE CONFERENCISTA CASCADE CONSTRAINTS;
DROP TABLE SEDE CASCADE CONSTRAINTS;

-- =========================
-- 1) TABLAS
-- =========================
CREATE TABLE SEDE (
  ID           NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
  NOMBRE_SEDE  VARCHAR2(100) NOT NULL,
  CIUDAD       VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_SEDE PRIMARY KEY (ID),
  CONSTRAINT UQ_SEDE_NOMBRE UNIQUE (NOMBRE_SEDE),
  CONSTRAINT UQ_SEDE_CIUDAD UNIQUE (CIUDAD)
);

CREATE TABLE CONFERENCISTA (
  ID        NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
  NOMBRE    VARCHAR2(100) NOT NULL,
  DOCUMENTO VARCHAR2(20)  NOT NULL,
  GENERO    CHAR(1)       NOT NULL,
  CONSTRAINT PK_CONFERENCISTA PRIMARY KEY (ID),
  CONSTRAINT UQ_CONF_NOMBRE UNIQUE (NOMBRE),
  CONSTRAINT UQ_CONF_DOC UNIQUE (DOCUMENTO),
  CONSTRAINT CK_CONF_GENERO CHECK (GENERO IN ('M','F'))
);

CREATE TABLE SALA (
  ID          NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
  NOMBRE_SALA VARCHAR2(100) NOT NULL,
  CAPACIDAD   NUMBER(5) DEFAULT 0 NOT NULL,
  ID_SEDE     NUMBER(10,0) NOT NULL,
  CONSTRAINT PK_SALA PRIMARY KEY (ID),
  CONSTRAINT UQ_SALA_NOMBRE UNIQUE (NOMBRE_SALA),
  CONSTRAINT CK_SALA_CAP CHECK (CAPACIDAD >= 0),
  CONSTRAINT FK_SALA_SEDE FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID)
);

CREATE TABLE CONFERENCIA_SALA (
  ID_CONFERENCISTA NUMBER(10,0) NOT NULL,
  ID_SALA          NUMBER(10,0) NOT NULL,
  FECHA            DATE         DEFAULT SYSDATE NOT NULL,
  VALOR_DIA        NUMBER(10,2) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_CONF_SALA PRIMARY KEY (ID_CONFERENCISTA, ID_SALA, FECHA),
  CONSTRAINT FK_CS_CONF FOREIGN KEY (ID_CONFERENCISTA) REFERENCES CONFERENCISTA(ID),
  CONSTRAINT FK_CS_SALA FOREIGN KEY (ID_SALA) REFERENCES SALA(ID),
  CONSTRAINT CK_CS_VALOR CHECK (VALOR_DIA >= 0)
);

-- =========================
-- 2) SEDES
-- =========================
INSERT INTO SEDE (NOMBRE_SEDE, CIUDAD) VALUES ('Sede Hogwarts',      'Bogota');
INSERT INTO SEDE (NOMBRE_SEDE, CIUDAD) VALUES ('Sede Stark Tower',   'Medellin');
INSERT INTO SEDE (NOMBRE_SEDE, CIUDAD) VALUES ('Sede Death Star',    'Cali');
INSERT INTO SEDE (NOMBRE_SEDE, CIUDAD) VALUES ('Sede Kame House',    'Barranquilla');
INSERT INTO SEDE (NOMBRE_SEDE, CIUDAD) VALUES ('Sede Gotham',        'Bucaramanga');
INSERT INTO SEDE (NOMBRE_SEDE, CIUDAD) VALUES ('Sede Rivendell',     'Cartagena');

-- =========================
-- 3) SALAS (12)
-- =========================
-- Hogwarts
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Gran Comedor', 200, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Hogwarts'));
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Defensa Oscura', 120, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Hogwarts'));

-- Stark Tower
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Arc Reactor', 180, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Stark Tower'));
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Avengers Briefing', 140, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Stark Tower'));

-- Death Star
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Hangar TIE', 160, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Death Star'));
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Consejo Imperial', 130, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Death Star'));

-- Kame House
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Torneo del Poder', 210, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Kame House'));
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Capsule Corp', 150, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Kame House'));

-- Gotham
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Batcave', 170, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Gotham'));
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Justice League', 190, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Gotham'));

-- Rivendell
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Consejo de Elrond', 160, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Rivendell'));
INSERT INTO SALA (NOMBRE_SALA, CAPACIDAD, ID_SEDE)
VALUES ('Sala Minas Tirith', 220, (SELECT ID FROM SEDE WHERE NOMBRE_SEDE='Sede Rivendell'));

-- =========================
-- 4) CONFERENCISTAS (14)
-- =========================
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Tony Stark',        'FAN6001', 'M'); -- 12/12 salas
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Natasha Romanoff',  'FAN6002', 'F');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Bruce Wayne',       'FAN6003', 'M');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Diana Prince',      'FAN6004', 'F');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Luke Skywalker',    'FAN6005', 'M');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Leia Organa',       'FAN6006', 'F');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Darth Vader',       'FAN6007', 'M');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Goku Son',          'FAN6008', 'M');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Bulma Brief',       'FAN6009', 'F');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Naruto Uzumaki',    'FAN6010', 'M');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Sakura Haruno',     'FAN6011', 'F');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Harry Potter',      'FAN6012', 'M');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Hermione Granger',  'FAN6013', 'F');
INSERT INTO CONFERENCISTA (NOMBRE, DOCUMENTO, GENERO) VALUES ('Aragorn Elessar',   'FAN6014', 'M');

-- =========================================================
-- 5) CONFERENCIAS
-- =========================================================

-- A) Tony Stark en TODAS las salas (12 conferencias)
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Gran Comedor'),
                                    DATE '2026-02-01', 900000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Defensa Oscura'),
                                    DATE '2026-02-02', 880000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Arc Reactor'),
                                    DATE '2026-02-03', 1200000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Avengers Briefing'),
                                    DATE '2026-02-04', 1100000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Hangar TIE'),
                                    DATE '2026-02-05', 950000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Consejo Imperial'),
                                    DATE '2026-02-06', 970000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Torneo del Poder'),
                                    DATE '2026-02-07', 1050000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Capsule Corp'),
                                    DATE '2026-02-08', 990000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Batcave'),
                                    DATE '2026-02-09', 1150000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Justice League'),
                                    DATE '2026-02-10', 1180000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Consejo de Elrond'),
                                    DATE '2026-02-11', 1020000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Tony Stark'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Minas Tirith'),
                                    DATE '2026-02-12', 1080000);

-- B) Luke Skywalker (7 conferencias) - repartidas
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Luke Skywalker'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Hangar TIE'),
                                    DATE '2026-03-01', 520000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Luke Skywalker'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Consejo Imperial'),
                                    DATE '2026-03-02', 540000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Luke Skywalker'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Gran Comedor'),
                                    DATE '2026-03-03', 500000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Luke Skywalker'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Avengers Briefing'),
                                    DATE '2026-03-04', 560000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Luke Skywalker'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Batcave'),
                                    DATE '2026-03-05', 590000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Luke Skywalker'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Consejo de Elrond'),
                                    DATE '2026-03-06', 610000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Luke Skywalker'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Torneo del Poder'),
                                    DATE '2026-03-07', 570000);

-- C) Goku (6 conferencias)
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Goku Son'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Torneo del Poder'),
                                    DATE '2026-03-08', 600000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Goku Son'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Capsule Corp'),
                                    DATE '2026-03-09', 580000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Goku Son'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Arc Reactor'),
                                    DATE '2026-03-10', 650000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Goku Son'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Gran Comedor'),
                                    DATE '2026-03-11', 540000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Goku Son'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Minas Tirith'),
                                    DATE '2026-03-12', 700000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Goku Son'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Hangar TIE'),
                                    DATE '2026-03-13', 630000);

-- D) Hermione (5 conferencias)
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Hermione Granger'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Defensa Oscura'),
                                    DATE '2026-03-14', 490000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Hermione Granger'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Gran Comedor'),
                                    DATE '2026-03-15', 470000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Hermione Granger'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Justice League'),
                                    DATE '2026-03-16', 520000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Hermione Granger'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Consejo de Elrond'),
                                    DATE '2026-03-17', 540000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Hermione Granger'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Avengers Briefing'),
                                    DATE '2026-03-18', 560000);

-- E) Naruto (4 conferencias)
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Naruto Uzumaki'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Batcave'),
                                    DATE '2026-03-19', 500000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Naruto Uzumaki'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Gran Comedor'),
                                    DATE '2026-03-20', 510000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Naruto Uzumaki'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Hangar TIE'),
                                    DATE '2026-03-21', 520000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Naruto Uzumaki'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Torneo del Poder'),
                                    DATE '2026-03-22', 540000);

-- F) Diana (4 conferencias)
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Diana Prince'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Justice League'),
                                    DATE '2026-03-23', 820000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Diana Prince'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Consejo de Elrond'),
                                    DATE '2026-03-24', 740000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Diana Prince'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Avengers Briefing'),
                                    DATE '2026-03-25', 760000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Diana Prince'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Minas Tirith'),
                                    DATE '2026-03-26', 780000);

-- G) Vader (3 conferencias)
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Darth Vader'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Consejo Imperial'),
                                    DATE '2026-03-27', 650000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Darth Vader'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Hangar TIE'),
                                    DATE '2026-03-28', 620000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Darth Vader'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Batcave'),
                                    DATE '2026-03-29', 700000);

-- H) Aragorn (3 conferencias)
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Aragorn Elessar'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Consejo de Elrond'),
                                    DATE '2026-03-30', 730000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Aragorn Elessar'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Minas Tirith'),
                                    DATE '2026-04-01', 760000);
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Aragorn Elessar'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Gran Comedor'),
                                    DATE '2026-04-02', 680000);

-- I) Extras pequeños 
INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Natasha Romanoff'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Arc Reactor'),
                                    DATE '2026-04-03', 780000);

INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Bruce Wayne'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Batcave'),
                                    DATE '2026-04-04', 800000);

INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Leia Organa'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Hangar TIE'),
                                    DATE '2026-04-05', 510000);

INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Bulma Brief'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Capsule Corp'),
                                    DATE '2026-04-06', 580000);

INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Harry Potter'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Defensa Oscura'),
                                    DATE '2026-04-07', 450000);

INSERT INTO CONFERENCIA_SALA VALUES ((SELECT ID FROM CONFERENCISTA WHERE NOMBRE='Sakura Haruno'),
                                    (SELECT ID FROM SALA WHERE NOMBRE_SALA='Sala Justice League'),
                                    DATE '2026-04-08', 520000);

COMMIT;


GRANT SELECT ON SEDE TO jcarreno;
GRANT SELECT ON SALA TO jcarreno;
GRANT SELECT ON CONFERENCISTA TO jcarreno;
GRANT SELECT ON CONFERENCIA_SALA TO jcarreno;

SELECT owner, table_name, select_priv, insert_priv, delete_priv, update_priv, references_priv, alter_priv, index_priv 
  FROM table_privileges
 WHERE grantee = 'JCARRENO'
 ORDER BY owner, table_name;
